name: Lint and Test

on: [push,pull_request,workflow_dispatch,workflow_call]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
          working-directory: ./
          skip-pkg-cache: true
          skip-cache: true
          skip-build-cache: true
          args: --timeout=99m

      - name: Test
        run: |
          make test
