name: Lint and Test

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:


jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "27.x"

      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: go mod download

      - name: Generate protobuf
        run: |
          make protoc

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54
          working-directory: ./
          skip-cache: true
          skip-save-cache: true
          args: --timeout=99m

      - name: Run tests
        run: |
          make test
